### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [sfu-dis/bztree#16]
Hi, I'm trying to build the BzTree but it doesn't seem to be working.
I've tried `cmake -DPMEM_BACKEND=PMDK -DCMAKE_BUILD_TYPE=Release ..` and `cmake -DPMEM_BACKEND=VOLATILE-DCMAKE_BUILD_TYPE=Debug ..` and neither compiled successfully. 

The errors were mostly that the allocator descriptor in pmwcas/mwcas was of the wrong type. I was able to fix most of those by using GetRaw where needed to get a pointer instead of a DescriptorGuard. I also needed to bump the CMakeLists.txt C++ version to std=c++17 for pmwcas. Once I fixed those errors, I was still getting errors about the use of google framework things in pmwcas and mwcas (both with and without GOOGLE_FRAMEWORK defined).

Was the BzTree meant to use some older version of pmwcas. If so, could you pin to that version? Otherwise, could someone please point me to a working build path?

Thanks!

**Comment by wangtzh** [comment]
Hi Srivastava - We're looking at it, will get back to you soon.

- Tianzheng

**Comment by wangtzh** [comment]
Hi @SrivastavaAnubhav - there have been some interface changes recently. @utashih and I just pulled in the updates from another fork we've been using. It should build now. Let us know if you hit other issues.

Tianzheng

**Comment by SrivastavaAnubhav** [comment]
Hi Tianzheng, the build is still failing when PMEM_BACKEND is set to VOLATILE or GOOGLE_FRAMEWORK is set to 0:
`fatal error: glog/logging.h: No such file or directory`

It does seem to build with PMDK, but I'm having trouble integrating it into my benchmark. I would like to just include the header file (`bztree.h`) and link with the built .so, but I'm finding it hard to track down all of the dependencies of `bztree.h` (`pmwcas.h` and all of its dependencies). Our benchmark does not currently use CMAKE. Do you know of an easy way to get a standalone interface for the BzTree?

Thanks,
Anubhav

**Comment by wangtzh** [comment]
Hi Anubhav - PMwCAS so far depends on glog for a lot of checks and logging, I'd suggest to just install it in your system or build your own (static or dynamic). The `GOOGLE_FRAMEWORK` knob currently should only work with bztree (@utashih please correct me if I'm wrong).

I checked in a change to avoid building pibench wrapper for non-PMDK backends, after that it builds under the volatile backend and GOOGLE_FRAMEWORK=0 (but again PMwCAS needs it, I have it installed in my system).

So my suggestion is to get glog built/installed, then you should be able to get a bztree.so to link with (in addition to linking with  the pmwcas library).

Tianzheng

**Comment by SrivastavaAnubhav** [comment]
Hi Tianzheng. I was able to get it built with both volatile and PMDK backends now, thanks! I'm now seeing some assertion failures. 
For example, the following program fails the `nleft > 0` assertion in `PrepareToSplit` (assertion fails on the 10th insert):
```
#include "bztree.h"

int main() {
    pmwcas::InitLibrary(pmwcas::DefaultAllocator::Create,
                        pmwcas::DefaultAllocator::Destroy,
                        pmwcas::LinuxEnvironment::Create,
                        pmwcas::LinuxEnvironment::Destroy);

    auto pool = new pmwcas::DescriptorPool(2000, 1, false);
    bztree::BzTree::ParameterSet param(256, 128, 256);
    auto tree = bztree::BzTree::New(param, pool);

    uint64_t k = 32; // arbitrary key
    bztree::ReturnCode ret;
    for (int i = 0; i < 10; ++i) {
        tree->Insert(reinterpret_cast<const char *>(&k), 8, 122);
        tree->Delete(reinterpret_cast<const char *>(&k), 8);
    }
}
```

I'm also seeing assertion failures at `assert(current_key || !is_leaf)` in `SearchRecordMeta`, when doing a random inserts and deletes (on 100 possible keys). Do you know what these errors might be? I noticed that the pibench wrapper does a `builtin_bswap` for find, remove and scan (but not insert or update). Is this necessary?

Also, there is a comma after `BUILD_TESTS` in `CMakeLists.txt` which prevents the option from defaulting to `ON`.

**Comment by wangtzh** [comment]
Hi Anubhav - Discussing here is fine. 

For assertion failures, we'll take a look first and get back to you. The built-in swap is for converting key bytes to big-endian order for inserts which is necessary. Re `BUILD_TESTS` - it should be fixed now.

**Comment by SrivastavaAnubhav** [comment]
Hi Tianzheng, the bswap fixed the errors, as far as I can tell. Just to make sure I'm testing correctly, are the following parameters appropriate? I'm assuming the `partition_count` parameter of `DescriptorPool` is the maximum number of threads, because if I set it lower than the number of threads it crashes. Is a constant value of 2000 ok for pool size? I wouldn't think I'd have to touch the ParameterSet params, except for fine tuning, right?

I'll be testing PMDK version tomorrow, so hopefully that goes smoothly too.

```
        auto pool = new pmwcas::DescriptorPool(2000, 20, false);
        bztree::BzTree::ParameterSet param(256, 128, 256);
```

**Comment by wangtzh** [comment]
Great to know it runs. Re partition count: it needs to be per-thread. So setting it to the max thread count (eg hyperthread on your machine) should be safe. Alternatively you can set it to the number of thread you're going to run experiments with. I vaguely remember we had a comment about this, noting the partitions are thread-local. 

Setting pool size to 2000 sounds a bit small to me, sometimes the execution can get stuck due to stragglers in epoch-based memory management. I suggest to use bigger values, e.g., 100k or (for debugging or just to be on the safe side) 1m.

Re bztree parameters - They control split/merge thresholds and leaf node size. In the past we used 1KB node size (the last parameter) and the default in bztree code is 4KB. You may want to fine tune them. See https://github.com/sfu-dis/bztree/blob/master/bztree.h#L558 for the definition.

**Comment by SrivastavaAnubhav** [comment]
For the PMDK build, I'm getting lots of warnings saying `No safe garbage scavenged`. After the `MultiInsert` tests passes, it seems to spew out endless amounts of this warning. Do you know what causes it, or is there a way to mute it?

**Comment by SrivastavaAnubhav** [comment]
Hi Tianzheng, actually I'm still confused about the bswap. I feel like the key should be swapped so that it's in big endian order in **all** operations, right? The pibench tests don't bswap for inserts.

Swapping for all operations leads to the assertion failures I mentioned before, would you mind taking a look? The following test should fail on the 10th insert (compiled just like bztree_tests).

```
#include "bztree.h"

int main() {
      pmwcas::InitLibrary(pmwcas::DefaultAllocator::Create,
                        pmwcas::DefaultAllocator::Destroy,
                        pmwcas::LinuxEnvironment::Create,
                        pmwcas::LinuxEnvironment::Destroy);
    auto pool = new pmwcas::DescriptorPool(2000, 1, false);
    bztree::BzTree::ParameterSet param(256, 128, 256);
    auto tree = bztree::BzTree::New(param, pool);

    std::cout << std::boolalpha;
    const uint64_t k = 1234; // arbitrary
    uint64_t kswapped = __builtin_bswap64(k);

    for (int i = 0; i < 10; ++i) {
        tree->Insert(reinterpret_cast<const char *>(&kswapped), 8, 122);
        tree->Delete(reinterpret_cast<const char *>(&kswapped), 8);
    } 
}
```

**Comment by wangtzh** [comment]
Closing since subsequent followups were done in emails.

**Comment by SrivastavaAnubhav** [comment]
Hi Tianzheng,

We were unable to resolve it in email. Ge mentioned that when consolidating a leaf node, the working thread might find the leaf node already frozen and this might account for some errors, but (as far as I know) hasn't implemented the solutions yet.
They mentioned you could either give up lock-freedom and just retraverse, or use more frozen bits.

I suspect there is an actual issue here, not just an assertion error, because
 1) removing the assertion causes a segfault
 2) When performing just inserts/deletes on a single key, the throughput is a few hundred million operations per second, which is beyond the limit of ~8-9 million that all other data structures give.

**Comment by wangtzh** [comment]
Hi Anubhav - I assumed your conversation with Ge is on-going in email, so there is no point leaving this one open here, whether it's resolved or not. My impression was this is a result of running insert + delete mix, and later boiled down to something that wasn't actually covered by the paper (which please note isn't written by us). 

@utashih can you please clarify on the status?
